from __future__ import annotations

import re
from pathlib import Path

from ideas_vault.frontmatter import IdeaMeta, parse

_IDEA_DIR_RE = re.compile(r"^(\d{3})-.+")


def _idea_number(folder: str) -> str:
    match = _IDEA_DIR_RE.match(folder)
    return match.group(1) if match else ""


def go_or_kill(verdict_value: str) -> str:
    """Collapse a verdict to a quick GO / KILL leaderboard flag (or a dash if unscored)."""
    if verdict_value == "GO":
        return "GO"
    if verdict_value in {"PIVOT", "NO-GO"}:
        return "KILL"
    return "-"


def rank(metas: list[IdeaMeta]) -> list[IdeaMeta]:
    """Sort ideas by adjusted score, highest first; unscored ideas sink to the bottom."""
    return sorted(
        metas,
        key=lambda meta: (meta.score is None, -(meta.score or 0), _idea_number(meta.folder)),
    )


def select(metas: list[IdeaMeta], numbers: list[str]) -> list[IdeaMeta]:
    """Pick ideas whose folder number matches ``numbers`` (preserving that order).

    Numbers may be given as ``1`` or ``001``; unknown numbers are skipped.
    """
    by_number = {_idea_number(meta.folder): meta for meta in metas}
    chosen: list[IdeaMeta] = []
    for raw in numbers:
        key = raw.zfill(3) if raw.isdigit() else raw
        meta = by_number.get(key)
        if meta is not None:
            chosen.append(meta)
    return chosen


#: Default kill threshold on the adjusted /40 score (NO-GO band starts below 15).
KILL_THRESHOLD = 15


def kill_list(metas: list[IdeaMeta], threshold: int = KILL_THRESHOLD) -> list[IdeaMeta]:
    """Scored ideas below ``threshold`` (worst first). Unscored ideas are excluded."""
    killed = [meta for meta in metas if meta.score is not None and meta.score < threshold]
    return sorted(killed, key=lambda meta: (meta.score or 0, _idea_number(meta.folder)))


def render_comparison(metas: list[IdeaMeta]) -> str:
    """Render a side-by-side comparison: attribute rows, one column per idea."""
    if not metas:
        return "No matching ideas to compare.\n"
    headers = ["Attribute", *[f"#{_idea_number(m.folder)}" for m in metas]]
    rows = [
        ("Title", [m.title for m in metas]),
        ("Score /40", ["" if m.score is None else str(m.score) for m in metas]),
        ("Verdict", [m.verdict for m in metas]),
        ("GO/KILL", [go_or_kill(m.verdict) for m in metas]),
        ("Market", [m.market_status for m in metas]),
        ("Date", [m.date for m in metas]),
    ]
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join(["---"] * len(headers)) + "|",
    ]
    for label, values in rows:
        lines.append("| " + " | ".join([label, *values]) + " |")
    return "\n".join(lines) + "\n"


def render_kill_list(metas: list[IdeaMeta], threshold: int = KILL_THRESHOLD) -> str:
    """Render the kill-list (ideas below ``threshold``) as a Markdown report."""
    killed = kill_list(metas, threshold)
    lines = [
        "# Kill list",
        "",
        f"Ideas scoring below {threshold}/40 - candidates to archive or pivot.",
        "",
        "| # | Title | Score /40 | Verdict | Folder |",
        "|---|---|---:|---|---|",
    ]
    for meta in killed:
        number = _idea_number(meta.folder)
        lines.append(f"| {number} | {meta.title} | {meta.score} | {meta.verdict} | {meta.folder} |")
    if not killed:
        lines.append("| - | (none below threshold) | | | |")
    lines.append("")
    return "\n".join(lines)


def collect(vault: Path) -> list[IdeaMeta]:
    metas: list[IdeaMeta] = []
    for child in sorted(vault.iterdir(), key=lambda p: p.name):
        if not child.is_dir() or child.name.startswith("_") or not _IDEA_DIR_RE.match(child.name):
            continue
        readme = child / "README.md"
        if not readme.exists():
            continue
        meta = parse(readme)
        if meta is None:
            continue
        meta.folder = child.name
        metas.append(meta)
    return sorted(metas, key=lambda meta: _idea_number(meta.folder))


def render_index(metas: list[IdeaMeta]) -> str:
    lines = [
        "# Ideas Vault Index",
        "",
        "Generated by `ivault index`. Scores are adjusted totals after the market modifier.",
        "",
        "| # | Title | Score /40 | Verdict | Date | Folder |",
        "|---|---|---:|---|---|---|",
    ]
    for meta in metas:
        score = "" if meta.score is None else str(meta.score)
        folder_link = f"[{meta.folder}]({meta.folder}/README.md)"
        lines.append(
            f"| {_idea_number(meta.folder)} | {meta.title} | {score} | "
            f"{meta.verdict} | {meta.date} | {folder_link} |"
        )
    lines.extend(
        [
            "",
            "Verdict legend: GO >= 30, PIVOT 15-29, NO-GO < 15. "
            "Any pillar <= 2 caps the verdict at PIVOT or NO-GO.",
            "",
        ]
    )
    return "\n".join(lines)


def regenerate(vault: Path) -> Path:
    path = vault / "INDEX.md"
    path.write_text(render_index(collect(vault)), encoding="utf-8", newline="\n")
    return path
