from __future__ import annotations

import re
from pathlib import Path

from ideas_vault.frontmatter import IdeaMeta, parse

_IDEA_DIR_RE = re.compile(r"^(\d{3})-.+")


def _idea_number(folder: str) -> str:
    match = _IDEA_DIR_RE.match(folder)
    return match.group(1) if match else ""


def go_or_kill(verdict_value: str) -> str:
    """Collapse a verdict to a quick GO / KILL leaderboard flag (or a dash if unscored)."""
    if verdict_value == "GO":
        return "GO"
    if verdict_value in {"PIVOT", "NO-GO"}:
        return "KILL"
    return "-"


def rank(metas: list[IdeaMeta]) -> list[IdeaMeta]:
    """Sort ideas by adjusted score, highest first; unscored ideas sink to the bottom."""
    return sorted(
        metas,
        key=lambda meta: (meta.score is None, -(meta.score or 0), _idea_number(meta.folder)),
    )


def collect(vault: Path) -> list[IdeaMeta]:
    metas: list[IdeaMeta] = []
    for child in sorted(vault.iterdir(), key=lambda p: p.name):
        if not child.is_dir() or child.name.startswith("_") or not _IDEA_DIR_RE.match(child.name):
            continue
        readme = child / "README.md"
        if not readme.exists():
            continue
        meta = parse(readme)
        if meta is None:
            continue
        meta.folder = child.name
        metas.append(meta)
    return sorted(metas, key=lambda meta: _idea_number(meta.folder))


def render_index(metas: list[IdeaMeta]) -> str:
    lines = [
        "# Ideas Vault Index",
        "",
        "Generated by `ivault index`. Scores are adjusted totals after the market modifier.",
        "",
        "| # | Title | Score /40 | Verdict | Date | Folder |",
        "|---|---|---:|---|---|---|",
    ]
    for meta in metas:
        score = "" if meta.score is None else str(meta.score)
        folder_link = f"[{meta.folder}]({meta.folder}/README.md)"
        lines.append(
            f"| {_idea_number(meta.folder)} | {meta.title} | {score} | "
            f"{meta.verdict} | {meta.date} | {folder_link} |"
        )
    lines.extend(
        [
            "",
            "Verdict legend: GO >= 30, PIVOT 15-29, NO-GO < 15. "
            "Any pillar <= 2 caps the verdict at PIVOT or NO-GO.",
            "",
        ]
    )
    return "\n".join(lines)


def regenerate(vault: Path) -> Path:
    path = vault / "INDEX.md"
    path.write_text(render_index(collect(vault)), encoding="utf-8", newline="\n")
    return path
