"""Export a vault as an Obsidian-ready folder of markdown notes.

One note per idea carries Dataview-compatible frontmatter (the four pillar fields
are not stored per-idea, so we surface the scored totals/verdict that *are*), plus
``[[wikilinks]]`` to sibling ideas that share a market status, and a generated MOC
(map of content) note that ranks every idea by adjusted ``/40`` with a GO/KILL flag.

It drops straight into an Obsidian vault with no plugin required; Dataview just makes
the frontmatter queryable. This stays offline-first: pure string templating, no deps.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from ideas_vault.frontmatter import IdeaMeta
from ideas_vault.index import _idea_number, collect, go_or_kill, rank

MOC_NAME = "Ideas MOC"


def _note_name(meta: IdeaMeta) -> str:
    """Stable, human-readable Obsidian note name (also the wikilink target)."""
    number = _idea_number(meta.folder)
    title = meta.title.strip() or meta.folder
    return f"{number} {title}" if number else title


def _safe_filename(name: str) -> str:
    """Strip characters Obsidian/the filesystem dislike, keeping the note name readable."""
    cleaned = "".join("-" if ch in '\\/:*?"<>|' else ch for ch in name)
    return " ".join(cleaned.split()).strip() or "untitled"


def _related(meta: IdeaMeta, by_market: dict[str, list[IdeaMeta]]) -> list[IdeaMeta]:
    """Ideas that share this idea's market status, excluding itself, idea-number order."""
    if not meta.market_status:
        return []
    siblings = [other for other in by_market[meta.market_status] if other.folder != meta.folder]
    return sorted(siblings, key=lambda other: _idea_number(other.folder))


def _frontmatter(meta: IdeaMeta) -> list[str]:
    score = "" if meta.score is None else str(meta.score)
    flag = go_or_kill(meta.verdict)
    return [
        "---",
        f"title: {meta.title}",
        f"number: {_idea_number(meta.folder)}",
        f"date: {meta.date}",
        f"verdict: {meta.verdict}",
        f"score: {score}",
        f"market_status: {meta.market_status}",
        f"flag: {flag}",
        f"folder: {meta.folder}",
        "tags: [idea-vault, idea]",
        "---",
    ]


def render_note(meta: IdeaMeta, by_market: dict[str, list[IdeaMeta]]) -> str:
    """Render a single idea note: Dataview frontmatter + body + related wikilinks."""
    score = "unscored" if meta.score is None else f"{meta.score}/40"
    flag = go_or_kill(meta.verdict)
    lines = _frontmatter(meta)
    lines += [
        "",
        f"# {_note_name(meta)}",
        "",
        f"- **Verdict:** {meta.verdict or '(unscored)'} ({flag})",
        f"- **Adjusted score:** {score}",
        f"- **Market status:** {meta.market_status or '(unset)'}",
        f"- **Source folder:** `{meta.folder}`",
        "",
        f"Back to [[{MOC_NAME}]].",
        "",
        "## Related ideas",
        "",
    ]
    related = _related(meta, by_market)
    if related:
        lines += [f"- [[{_note_name(other)}]] ({other.market_status})" for other in related]
    else:
        lines.append("_No sibling ideas share this market status yet._")
    lines.append("")
    return "\n".join(lines)


def render_moc(metas: list[IdeaMeta]) -> str:
    """Render the map-of-content note: every idea ranked by adjusted /40 with a GO/KILL flag."""
    lines = [
        "---",
        "title: Ideas MOC",
        "tags: [idea-vault, moc]",
        "---",
        f"# {MOC_NAME}",
        "",
        "Generated by `ivault export --format obsidian`. "
        "Ideas are ranked by adjusted score; the flag collapses the verdict to GO or KILL.",
        "",
        "| Rank | # | Idea | Score /40 | Verdict | Flag |",
        "|---:|---|---|---:|---|---|",
    ]
    for position, meta in enumerate(rank(metas), start=1):
        score = "" if meta.score is None else str(meta.score)
        flag = go_or_kill(meta.verdict)
        lines.append(
            f"| {position} | {_idea_number(meta.folder)} | [[{_note_name(meta)}]] | "
            f"{score} | {meta.verdict} | {flag} |"
        )
    lines += [
        "",
        "Verdict legend: GO >= 30, PIVOT 15-29, NO-GO < 15. "
        "Any pillar <= 2 caps the verdict at PIVOT or NO-GO.",
        "",
    ]
    return "\n".join(lines)


def export_obsidian(vault: Path, out: str | Path | None = None) -> Path:
    """Write an Obsidian note per idea plus a MOC note into ``out`` (default ``<vault>/obsidian``).

    Returns the output directory. Re-running is idempotent: existing notes are overwritten.
    """
    metas = collect(vault)
    out_dir = Path(out) if out else vault / "obsidian"
    out_dir.mkdir(parents=True, exist_ok=True)

    by_market: dict[str, list[IdeaMeta]] = defaultdict(list)
    for meta in metas:
        if meta.market_status:
            by_market[meta.market_status].append(meta)

    for meta in metas:
        filename = f"{_safe_filename(_note_name(meta))}.md"
        (out_dir / filename).write_text(
            render_note(meta, by_market), encoding="utf-8", newline="\n"
        )

    (out_dir / f"{MOC_NAME}.md").write_text(render_moc(metas), encoding="utf-8", newline="\n")
    return out_dir
